name: Kernel Build by tejat
# 实际上是deepseek和我一起写的（

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git make gcc bc bison flex libssl-dev

      - name: Clone toolchain
        run: |
          git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git toolchain
          echo "Clone Again"
          git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git toolchain2
          echo "Move"
          mv toolchain2 clang-r416183b1
          mkdir -p ../prebuilts/clang/host/linux-x86/
          mv clang-r416183b1 ../prebuilts/clang/host/linux-x86/

      - name: Set PATH
        run: |
          echo "PATH=$GITHUB_WORKSPACE/toolchain/bin:$PATH" >> $GITHUB_ENV

      - name: Clone kernel source
        run: |
          git clone https://github.com/Remedgit/android_kernel_kirin9000.git kernel-source

      - name: Configure and Build
        run: |
          cd kernel-source
          echo "Now PWD is: "
          pwd
          mkdir -p out
          ls arch/arm64/configs/merge_baltimore_defconfig
          export ARCH=arm64
          export SUBARCH=arm64
          echo $ARCH
          echo $SUBARCH
          make -j8 KBUILD_BUILD_USER=tejat KBUILD_BUILD_HOST=GithubActionAutoBuild ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnuabeihf- CC=clang LD=ld.lld HOSTCC=clang HOSTLD=ld.lld O=out KCFLAGS+=-Wno-error merge_baltimore_defconfig
          make -j8 KBUILD_BUILD_USER=tejat KBUILD_BUILD_HOST=GithubActionAutoBuild ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnuabeihf- CC=clang LD=ld.lld HOSTCC=clang HOSTLD=ld.lld O=out KCFLAGS+=-Wno-error

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: ./kernel-source/out/arch/arm64/boot/Image.gz
